### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by KSathiya** [TBXark/Ruler#1]
I am using the same ruler app code in an existing application, it throws lot of compiler error,

I have installed pod.

The errors are like binary operator(s1 =+ )cannot be used in SCNVector3, average method is not available.

**Comment by tbxark** [comment]
Add [SceneKit+Extension.swift](https://github.com/TBXark/Ruler/blob/master/Ruler/General/Category/SceneKit%2BExtension.swift)  for your project
