### ISSUE TITLE
No such module Rswift

### ISSUE THREAD

**Issue by ykguler** [TBXark/Ruler#3]
Followed the readme to compile locally, got an error on R.generated.swift line 7; "import Rswift" --> no such module 'Rswift'

**Comment by tbxark** [comment]
```shell 
git clone git@github.com:TBXark/Ruler.git
cd Ruler
pod install
open Ruler.xcworkspace
```

??  I can compile normally, you can refer to the R.Swift documentation to view the configuration process
https://github.com/mac-cain13/R.swift

**Comment by ykguler** [comment]
Tried again and it worked, I think the problem happened because I ran pod install after opening the workspace.. Thanks for the fast reply!

**Comment by snapfinger** [comment]
I encountered the same problem. Though I followed the sequence of steps, it still didn't work. Emm...
