### ISSUE TITLE
I can not start this app

### ISSUE THREAD

**Issue by UdonDa** [TBXark/Ruler#4]
This repository is cloned and built, the first screen is displayed, but the following error has appeared and it can not be used.

I am in trouble because I do not know how to solve it. please tell me!

<img width="1182" alt="2018-05-05 20 43 27" src="https://user-images.githubusercontent.com/25411643/39662941-fe9171d8-50a4-11e8-9eb5-fe17131b0338.png">

**Comment by tc1993** [comment]
I also encountered this problem, did you solve it?
